name: Check IDM

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  schedule:
    - cron: "25 23 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Config git
        run: |
          git config --local user.email "78083448+JaimeZeng@users.noreply.github.com"
          git config --local user.name "JaimeZeng"
      - name: Check IDM
        run: |
          cd ./check
          bash check-idm.sh
          git commit -am "version: update IDM"
      - name: Push IDM changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}
